---
- hosts: all
  become: yes
  vars:
    hostname: "ucibox"
  tasks:
    - name: Make sure the current version of ‘sysstat’ is installed.
      dnf:
        name: python3-dnf
        state: latest

    - name: Make sure the current version of ‘sysstat’ is installed.
      dnf:
        name: sysstat
        state: latest