---

- name: Update apt cache.
  apt:
    update_cache: True

- name: Make sure the current version of ‘mysql-server’ is installed.
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - net-tools
    - python3-pip